{% set name = "unicodedata2" %}
{% set version = "16.0.0" %}
{% set sha256 = "05488d6592b59cd78b61ec37d38725416b2df62efafa6a0d63a631b27aa474fc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - unicodedata2

about:
  home: https://github.com/mikekap/unicodedata2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: unicodedata backport/updates to python 3 and python 2.
  description: unicodedata backport/updates to python 3 and python 2.
  dev_url: https://github.com/mikekap/unicodedata2

extra:
  recipe-maintainers:
    - CJ-Wright
    - dopplershift
