{% set name = "unicodedata2" %}
{% set version = "18.0.0" %}
{% set sha256 = "a9536291a5204caf6423ca7c56131d44f2aafc2fada35ff3a5eac82f7f8c62a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - unicodedata2

about:
  home: https://github.com/mikekap/unicodedata2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: unicodedata backport/updates to python 3 and python 2.
  description: unicodedata backport/updates to python 3 and python 2.
  dev_url: https://github.com/mikekap/unicodedata2

extra:
  recipe-maintainers:
    - CJ-Wright
    - dopplershift
